name: CI E2E - Playwright Tests with Allure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    # MySQL service setup
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    # Environment variables
    env:
      TEST_BASE_URL: https://rahulshettyacademy.com/client
      TEST_USERNAME: roshan.thomas@test.com
      TEST_PASSWORD: Password2.
      TEST_DB_HOST: 127.0.0.1
      TEST_DB_PORT: 3306
      TEST_DB_USER: root
      TEST_DB_PASS: root123
      TEST_DB_NAME: testdb
      ORDER_LOG_PATH: C:\\PlaywrightAutomationGITHUB\\PlaywrightXFramework\\logging\\orderLogs.txt

    steps:
      # 1️⃣
