name: CI E2E - Playwright Tests with Allure built using PlaywrightXFramework developed by roshanwatzaptester

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  playwright_pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      TEST_BASE_URL: https://rahulshettyacademy.com/client
      TEST_USERNAME: roshan.thomas@test.com
      TEST_PASSWORD: Password2.
      TEST_DB_HOST: 127.0.0.1
      TEST_DB_PORT: 3306
      TEST_DB_USER: root
      TEST_DB_PASS: root123
      TEST_DB_NAME: testdb
      ORDER_LOG_PATH: ./logging/orderLogs.txt

    steps:
      - name: Checkout repository | (PlaywrightXFramework_roshanwatzaptester)
        uses: actions/checkout@v4

      - name: Setup Node.js | (PlaywrightXFramework_roshanwatzaptester)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies | (PlaywrightXFramework_roshanwatzaptester)
        run: npm ci

      - name: Install Playwright Browsers | (PlaywrightXFramework_roshanwatzaptester)
        run: npx playwright install --with-deps

      - name: Wait for MySQL | (PlaywrightXFramework_roshanwatzaptester)
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -P3306 -uroot -proot123 && break
            sleep 2
          done

      - name: Initialize database and tables | (PlaywrightXFramework_roshanwatzaptester)
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot123 testdb <<'EOF'
          CREATE TABLE IF NOT EXISTS test_data (
            id INT PRIMARY KEY AUTO_INCREMENT,
            testProduct VARCHAR(255),
            testCountry VARCHAR(100),
            username VARCHAR(50),
            password VARCHAR(50),
            logPath VARCHAR(500)
          );

          INSERT INTO test_data (id, testProduct, testCountry, username, password, logPath)
          VALUES (1, 'ZARA COAT 3', 'India', 'roshan.thomas@test.com', 'Password2.', './logging/orderLogs.txt')
          ON DUPLICATE KEY UPDATE testProduct='ZARA COAT 3';

          CREATE TABLE IF NOT EXISTS order_logs (
            Order_id VARCHAR(200),
            timestamps VARCHAR(200),
            testername VARCHAR(200),
            browserName VARCHAR(255),
            testcase_name VARCHAR(500),
            runId VARCHAR(500)
          );
          EOF

      - name: Run Playwright tests | (PlaywrightXFramework_roshanwatzaptester)
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure report | (PlaywrightXFramework_roshanwatzaptester)
        run: |
          rm -rf ./allure-report
          npx allure generate ./allure-results -o ./allure-report

      - name: Combine Allure results and report into PFX_AllureReports | (PlaywrightXFramework_roshanwatzaptester)
        run: |
          rm -rf PFX_AllureReports
          mkdir -p PFX_AllureReports
          cp -r allure-results PFX_AllureReports/
          cp -r allure-report PFX_AllureReports/

      - name: Upload PFX_AllureReports artifact | (PlaywrightXFramework_roshanwatzaptester)
        uses: actions/upload-artifact@v4
        with:
          name: PFX_AllureReports
          path: PFX_AllureReports

      - name: Export DB dump | (PlaywrightXFramework_roshanwatzaptester)
        run: mysqldump -h 127.0.0.1 -P 3306 -uroot -proot123 testdb > db_dump.sql

      - name: Upload DB Dump | (PlaywrightXFramework_roshanwatzaptester)
        uses: actions/upload-artifact@v4
        with:
          name: mysql-dump
          path: db_dump.sql

      - name: Export order_logs to CSV (with headers) | (PlaywrightXFramework_roshanwatzaptester)
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot123 --batch \
          -e "SELECT * FROM order_logs;" testdb | sed 's/\t/,/g' > order_logs.csv

      - name: Upload order_logs CSV | (PlaywrightXFramework_roshanwatzaptester)
        uses: actions/upload-artifact@v4
        with:
          name: order-logs-csv
          path: order_logs.csv

      - name: Upload Order Logs | (PlaywrightXFramework_roshanwatzaptester)
        uses: actions/upload-artifact@v4
        with:
          name: order-logs
          path: ./logging/orderLogs.txt
